config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :listings
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/my-feed', to: 'pages#feed'
  get '/categories/:id', to: 'categories#show'
  post "/follow_category/:user_id/:category_id", to: 'follows#follow_category'
  delete "/unfollow_category/:user_id/:category_id", to: 'follows#unfollow_category'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :category
  belongs_to :user
  validates :item_name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  has_one_attached :listing_img

  require 'link_thumbnailer'
  require 'open-uri'

  def url?
    uri = URI.parse(link)
    %w( http https ).include?(uri.scheme)
  rescue URI::BadURIError
    false
  rescue URI::InvalidURIError
    false
  end
  
  def self.blank
    open("http://homepages.neiu.edu/~nchaudhr/Frames/images/gray.jpg")
  end

  def link_title
    @thumb = LinkThumbnailer.generate(link)
    @thumb.title
  end

  def link_description
    @thumb = LinkThumbnailer.generate(link)
    @thumb.description
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :verify_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    unless @listing.listing_img.attached?
      @listing.listing_img.attach(io: Listing.blank, filename: "listing_img",content_type: Listing.blank.content_type_parse.first )
    end
    if @listing.url?
      @listing.item_name= @listing.link_title
      @listing.description= @listing.link_description
    end

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:item_name, :description, :category_id, :user_id, :listing_img, :link)
    end

    def verify_user
      redirect_to user_path(current_user) unless @listing.user == current_user
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %><br>
    <%= form.text_field :item_name %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div class="field form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name%>
  </div>

  <div class="field">
    <%= form.label :item_image %><br>
    <%= form.file_field :listing_img %>
  </div>

  <%unless @listing.user%>
    <div class="field">
      <%= form.label :insert_link_to_autofill_item_name_and_description %>
      <%= form.text_field :link %>
    </div>
  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<a href=<%="#{listing_path(@listing)}"%> class="btn btn-primary">Return to Listing</a>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<% Category.all.each do |category| %>
  <a href=<%="/categories/#{category.id}"%> class="btn btn-category"><%=category.name%></a>
<% end %>

<h1>Listings</h1>
<a href=<%=new_listing_path%> class="btn btn-primary">Create Listing</a>

<div class ="row">
  <% @listings.each do |listing| %>
    <div class="col-3" style="padding: 10px;">
      <div class="card" style="width: 100%;">
        <div class="card-body">
          <h5 class="card-title"><%= listing.item_name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= listing.category.name %></h6>
          <div class="card-img">
            <img src="<%= url_for(listing.listing_img) %>" class="card-img-top" alt="...">
          </div>
          <p class="card-text"><%= truncate(listing.description, :length => 100) %></p>
          <a href=<%="#{listing_path(listing)}"%> class="btn btn-primary">View</a>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<a href=<%="#{listings_path}"%> class="btn btn-primary">View All Listings</a>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div style="width:50%; margin:auto">
  <a href=<%="#{listings_path}"%> class="btn btn-primary">View All Listings</a>
  

  <h1><%= @listing.item_name %></h1>
  <a href=<%="/categories/#{@listing.category.id}"%> class="btn btn-primary"><%= @listing.category.name %></a>
  <%if logged_in? && @listing.user.id == current_user.id%>
    <a href=<%="#{edit_listing_path(@listing)}"%> class="btn btn-info">Edit Listing</a>

    <a data-method="delete" href=<%="#{@listing}"%> class="btn btn-danger">Delete</a>

  <%end%>
  <p><strong>Seller: </strong>  
  <%= link_to @listing.user.username, user_path(@listing.user), {:style=>'color:blue;'} %></p>
  <div class="container-img">
    <img src = "<%= url_for(@listing.listing_img) %>" class="container-img"/>
  </div>
  <h5>Description:</h5>
  <p><%= @listing.description %></p>
</div>