config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :listings
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/my-feed', to: 'pages#feed'
  get '/categories/:id', to: 'categories#show'
  post "/follow_category/:user_id/:category_id", to: 'follows#follow_category'
  delete "/unfollow_category/:user_id/:category_id", to: 'follows#unfollow_category'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord

  include BCrypt

  has_many :listings, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :categories, through: :follows
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password_hash, presence: true
  has_one_attached :user_img

  extend FriendlyId
  friendly_id :username, use: :slugged

  def full_name
    p "#{first_name} #{last_name}"
  end

  def feed_listing
    @feed = []
    categories.each { |cat| @feed = @feed + cat.listings }
    @feed.sort_by(&:created_at).reverse
  end

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
  
  def self.blank
    open("https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :verify_user, only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    redirect_to user_path(current_user) if logged_in?
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    unless @user.user_img.attached?
      @user.user_img.attach(io: User.blank, filename: "user_img",content_type: User.blank.content_type_parse.first )
    end

    respond_to do |format|
      if @user.save
        @user.password= user_params[:password_hash]
        @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @password_hash = @user.password_hash
    @user.assign_attributes(user_params)
    @user.password= user_params[:password_hash]
    if user_params[:password_hash].length == 0
      @user.password_hash = @password_hash
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    def verify_user
      redirect_to user_path(current_user) unless @user == current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password_hash, :username, :user_img)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password_hash %>
  </div>

  <div class="field">
    <%= form.label :profile_picture %>
    <%= form.file_field :user_img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', user: @user %>

<a href=<%="#{user_path(@user)}"%> class="btn btn-primary">Return to Profile</a>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class ="row">
  <% @users.each do |user| %>
    <div class="col-3" style="padding: 10px;">
      <div class="card" style="width: 100%;">
        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <div class="card-img">
            <img src="<%= url_for(user.user_img) %>" class="card-img-top" alt="...">
          </div>
          <a href=<%="#{user_path(user)}"%> class="btn btn-primary">View</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Creating Profile</h1>

<%= render 'form', user: @user %>

<a href=<%="#{users_path}"%> class="btn btn-primary">View All Users</a>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div style="width:50%; margin:auto">
  <a href=<%="#{users_path}"%> class="btn btn-primary">Return to Users</a>
  
  <h1><strong>Username: </strong><%= @user.username %></h1>
  <%if logged_in? && @user.id == current_user.id%>

    <a href=<%="#{edit_user_path(@user)}"%> class="btn btn-info">Edit Profile</a>
    <a data-method="delete" href=<%="#{@user}"%> class="btn btn-danger">Delete Account</a>
    <p><strong>Name: </strong><%= @user.full_name %></p>
    <p><strong>Email: </strong><%= @user.email %></p>

  <%end%>
  <div class="container-user-img">
    <img src = "<%= url_for(@user.user_img) %>" class="user-img"/>
  </div>
</div>

<div>
  <strong>User Listings:</strong>

  <div class ="row">
    <% @user.listings.each do |listing| %>
      <div class="col-3" style="padding: 10px;">
        <div class="card" style="width: 100%;">
          <div class="card-body">
            <h5 class="card-title"><%= listing.item_name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= listing.category.name %></h6>
            <div class="card-img">
              <img src="<%= url_for(listing.listing_img) %>" class="card-img-top" alt="...">
            </div>
            <p class="card-text"><%= truncate(listing.description, :length => 100) %></p>
            <a href=<%="#{listing_path(listing)}"%> class="btn btn-primary">View</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>